name: Django CI

on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports: ['6379:6379']
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: test@123
          MYSQL_DATABASE: djnagopipe
          MYSQL_ROOT_HOST: '%'              # ✅ Allow root login from any host
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -ptest@123 --silent"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=10
    env:
      SECRET_KEY: test
      DEBUG: True
      REDIS_URL: redis://localhost:6379/1
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt
    - run: sudo apt-get update && sudo apt-get install -y mysql-client
    - run: mysql -h 127.0.0.1 -u root -p'test@123' -e "SHOW DATABASES;"
    - run: python manage.py migrate
    - run: python manage.py test
    - run: docker info
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/django-app:latest .
    - run: docker push ${{ secrets.DOCKER_USERNAME }}/django-app:latest